[2025-03-07 13:55:00,348][src.utils.utils][INFO] - Disabling python warnings! <cfg.extras.ignore_warnings=True>
[2025-03-07 13:55:00,349][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-03-07 13:55:00,349][src.utils.rich_utils][WARNING] - No tags provided in config. Prompting user to input tags...
[2025-03-07 13:55:01,930][src.utils.rich_utils][INFO] - Tags: ['dev']
[2025-03-07 13:55:01,940][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-03-07 13:55:01,940][src.utils.rich_utils][WARNING] - Field 'data' not found in config. Skipping 'data' config printing...
[2025-03-07 13:55:01,940][src.utils.rich_utils][WARNING] - Field 'model' not found in config. Skipping 'model' config printing...
[2025-03-07 13:55:01,941][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2025-03-07 13:55:01,972][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/Users/wangzh/Desktop/ShanghaiTech/Spring_2025/ICCP2025/mitsuba3-workflow/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/Users/wangzh/Desktop/ShanghaiTech/Spring_2025/ICCP2025/mitsuba3-workflow/src/train.py", line 27, in train
    log.info(f"Instantiating trainer <{cfg.trainer._target_}>")
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key '_target_' is not in struct
    full_key: trainer._target_
    object_type=dict
[2025-03-07 13:55:01,976][src.utils.utils][INFO] - Output dir: /Users/wangzh/Desktop/ShanghaiTech/Spring_2025/ICCP2025/mitsuba3-workflow/logs/fit_image_test/runs/2025-03-07_13-55-00
