[2025-03-07 16:58:02,948][src.utils.utils][INFO] - Disabling python warnings! <cfg.extras.ignore_warnings=True>
[2025-03-07 16:58:02,948][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-03-07 16:58:02,950][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-03-07 16:58:02,951][src.utils.rich_utils][WARNING] - Field 'data' not found in config. Skipping 'data' config printing...
[2025-03-07 16:58:02,951][src.utils.rich_utils][WARNING] - Field 'model' not found in config. Skipping 'model' config printing...
[2025-03-07 16:58:02,951][src.utils.rich_utils][WARNING] - Field 'callbacks' not found in config. Skipping 'callbacks' config printing...
[2025-03-07 16:58:02,964][__main__][INFO] - Instantiating trainer <src.models.trainer_image.ImageTrainer>
[2025-03-07 16:58:03,143][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/Users/wangzh/Desktop/ShanghaiTech/Spring_2025/ICCP2025/mitsuba3-workflow/src/models/trainer_image.py", line 39, in __init__
    self.optimizer = mi.ad.Adam(lr=learning_rate, prams={key: self.params[key] for key in self.keys_to_optimize})
TypeError: Adam.__init__() got an unexpected keyword argument 'prams'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wangzh/Desktop/ShanghaiTech/Spring_2025/ICCP2025/mitsuba3-workflow/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/Users/wangzh/Desktop/ShanghaiTech/Spring_2025/ICCP2025/mitsuba3-workflow/src/train.py", line 28, in train
    trainer: MitsubaTrainer = hydra.utils.instantiate(cfg.trainer)
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/opt/miniconda3/envs/mi3/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.models.trainer_image.ImageTrainer':
TypeError("Adam.__init__() got an unexpected keyword argument 'prams'")
full_key: trainer
[2025-03-07 16:58:03,147][src.utils.utils][INFO] - Output dir: /Users/wangzh/Desktop/ShanghaiTech/Spring_2025/ICCP2025/mitsuba3-workflow/logs/fit_image_test/runs/2025-03-07_16-58-02
